stages:
  - test
  - build-and-deploy

.run_on_dockerhost: &run_on_dockerhost
  tags:
    - docker20
  before_script:
    - python3 ams2rst_script/ConvertAMS2RST.py AimmsXLLibrary.ams
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  image: gitlab.aimms.com:5050/other/dockerdev/documentation:latest

linkcheck:
  <<: *run_on_dockerhost
  stage: test
  script:
    - python3 -msphinx -W -b linkcheck . _build/linkcheck
  retry: 1

spellcheck:
  <<: *run_on_dockerhost
  stage: test
  script:
    - python3 -msphinx -W --keep-going -b spelling . _build/spelling

build:
  <<: *run_on_dockerhost
  stage: test
  script:
    - python3 -msphinx -W --keep-going -b html . _build/html 

deploy:
  <<: *run_on_dockerhost
  stage: build-and-deploy
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
    - when: never
  script:
    - python3 -msphinx -b html . _build/html
    - python3 -msphinx.ext.intersphinx _build/html/objects.inv > _build/html/help_index_aimmsxllibrary.txt
    - bash load_ssh_key_for_deploy.sh
    - rsync -rt _build/html/ support@data.aimms.com:/home/aimms/www/documentation.aimms.com/aimmsxllibrary/
  retry: 1
